import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
ThemeData lighttheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF1B5E20), 
    onPrimary: Colors.white,
    primaryContainer: Color(0xFFE8F5E8), 
    onPrimaryContainer: Color(0xFF1B5E20),
    secondary: Color(0xFF2E7D32), 
    onSecondary: Colors.white,
    secondaryContainer: Color(0xFFF1F8E9),
    onSecondaryContainer: Color(0xFF1B5E20),
    tertiary: Color(0xFF4CAF50), 
    onTertiary: Colors.white,
    tertiaryContainer: Color(0xFFE8F5E8),
    onTertiaryContainer: Color(0xFF1B5E20),
    error: Color(0xFFD32F2F),
    onError: Colors.white,
    errorContainer: Color(0xFFFFEBEE),
    onErrorContainer: Color(0xFFB71C1C),
    surface: Color(0xFFFAFAFA), 
    onSurface: Color(0xFF1A1A1A),
    surfaceContainerHighest: Color(0xFFF0F0F0),
    onSurfaceVariant: Color(0xFF616161),
    outline: Color(0xFFE0E0E0),
    outlineVariant: Color(0xFFF0F0F0),
    shadow: Colors.black12,
    scrim: Colors.black54,
    inverseSurface: Color(0xFF2A2A2A),
    onInverseSurface: Color(0xFFFAFAFA),
    inversePrimary: Color(0xFF81C784),
    surfaceTint: Color(0xFF1B5E20),
  ),
  textTheme: TextTheme(
    headlineLarge: GoogleFonts.inter(
      fontSize: 32,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.5,
      color: const Color(0xFF1B5E20),
    ),
    headlineMedium: GoogleFonts.inter(
      fontSize: 28,
      fontWeight: FontWeight.w600,
      letterSpacing: 0,
      color: const Color(0xFF1B5E20),
    ),
    headlineSmall: GoogleFonts.inter(
      fontSize: 24,
      fontWeight: FontWeight.w600,
      letterSpacing: 0,
      color: const Color(0xFF1B5E20),
    ),
    titleLarge: GoogleFonts.inter(
      fontSize: 22,
      fontWeight: FontWeight.w600,
      letterSpacing: 0,
      color: const Color(0xFF1A1A1A),
    ),
    titleMedium: GoogleFonts.inter(
      fontSize: 16,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.15,
      color: const Color(0xFF1A1A1A),
    ),
    titleSmall: GoogleFonts.inter(
      fontSize: 14,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.1,
      color: const Color(0xFF1A1A1A),
    ),
    bodyLarge: GoogleFonts.inter(
      fontSize: 16,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.15,
      color: const Color(0xFF1A1A1A),
    ),
    bodyMedium: GoogleFonts.inter(
      fontSize: 14,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      color: const Color(0xFF424242),
    ),
    bodySmall: GoogleFonts.inter(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.4,
      color: const Color(0xFF616161),
    ),
  ),
  appBarTheme: AppBarTheme(
    elevation: 0,
    scrolledUnderElevation: 2,
    backgroundColor: const Color(0xFF1B5E20),
    foregroundColor: Colors.white,
    surfaceTintColor: const Color(0xFF1B5E20),
    centerTitle: true,
    titleTextStyle: GoogleFonts.inter(
      fontSize: 20,
      fontWeight: FontWeight.w600,
      color: Colors.white,
      letterSpacing: 0,
    ),
    iconTheme: const IconThemeData(
      color: Colors.white,
      size: 24,
    ),
  ),
  cardTheme: const CardThemeData(
    elevation: 2,
    shadowColor: Colors.black12,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.all(Radius.circular(16)),
    ),
    color: Colors.white,
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      elevation: 2,
      backgroundColor: const Color(0xFF1B5E20),
      foregroundColor: Colors.white,
      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
      ),
      textStyle: GoogleFonts.inter(
        fontSize: 14,
        fontWeight: FontWeight.w600,
        letterSpacing: 0.1,
      ),
    ),
  ),
  bottomAppBarTheme: const BottomAppBarTheme(
    color: Color(0xFFFAFAFA),
    elevation: 8,
  ),
  iconTheme: const IconThemeData(
    color: Color(0xFF424242),
    size: 24,
  ),
  drawerTheme: const DrawerThemeData(
    backgroundColor: Color(0xFFFAFAFA),
    surfaceTintColor: Color(0xFFFAFAFA),
  ),
);
ThemeData darktheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF66BB6A), 
    onPrimary: Color(0xFF1B5E20),
    primaryContainer: Color(0xFF2E7D32), 
    onPrimaryContainer: Color(0xFFE8F5E8),
    secondary: Color(0xFF4CAF50), 
    onSecondary: Color(0xFF1B5E20),
    secondaryContainer: Color(0xFF388E3C),
    onSecondaryContainer: Color(0xFFF1F8E9),
    tertiary: Color(0xFF81C784), 
    onTertiary: Color(0xFF1B5E20),
    tertiaryContainer: Color(0xFF2E7D32),
    onTertiaryContainer: Color(0xFFE8F5E8),
    error: Color(0xFFE57373),
    onError: Color(0xFF1A1A1A),
    errorContainer: Color(0xFFD32F2F),
    onErrorContainer: Color(0xFFFFEBEE),
    surface: Color(0xFF121212), 
    onSurface: Color(0xFFE0E0E0),
    surfaceContainerHighest: Color(0xFF1E1E1E),
    onSurfaceVariant: Color(0xFFBDBDBD),
    outline: Color(0xFF616161),
    outlineVariant: Color(0xFF424242),
    shadow: Colors.black87,
    scrim: Colors.black87,
    inverseSurface: Color(0xFFE0E0E0),
    onInverseSurface: Color(0xFF121212),
    inversePrimary: Color(0xFF1B5E20),
    surfaceTint: Color(0xFF66BB6A),
  ),
  textTheme: TextTheme(
    headlineLarge: GoogleFonts.inter(
      fontSize: 32,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.5,
      color: const Color(0xFF66BB6A),
    ),
    headlineMedium: GoogleFonts.inter(
      fontSize: 28,
      fontWeight: FontWeight.w600,
      letterSpacing: 0,
      color: const Color(0xFF66BB6A),
    ),
    headlineSmall: GoogleFonts.inter(
      fontSize: 24,
      fontWeight: FontWeight.w600,
      letterSpacing: 0,
      color: const Color(0xFF66BB6A),
    ),
    titleLarge: GoogleFonts.inter(
      fontSize: 22,
      fontWeight: FontWeight.w600,
      letterSpacing: 0,
      color: const Color(0xFFE0E0E0),
    ),
    titleMedium: GoogleFonts.inter(
      fontSize: 16,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.15,
      color: const Color(0xFFE0E0E0),
    ),
    titleSmall: GoogleFonts.inter(
      fontSize: 14,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.1,
      color: const Color(0xFFE0E0E0),
    ),
    bodyLarge: GoogleFonts.inter(
      fontSize: 16,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.15,
      color: const Color(0xFFE0E0E0),
    ),
    bodyMedium: GoogleFonts.inter(
      fontSize: 14,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      color: const Color(0xFFBDBDBD),
    ),
    bodySmall: GoogleFonts.inter(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.4,
      color: const Color(0xFF9E9E9E),
    ),
  ),
  appBarTheme: AppBarTheme(
    elevation: 0,
    scrolledUnderElevation: 2,
    backgroundColor: const Color(0xFF1B5E20),
    foregroundColor: Colors.white,
    surfaceTintColor: const Color(0xFF1B5E20),
    centerTitle: true,
    titleTextStyle: GoogleFonts.inter(
      fontSize: 20,
      fontWeight: FontWeight.w600,
      color: Colors.white,
      letterSpacing: 0,
    ),
    iconTheme: const IconThemeData(
      color: Colors.white,
      size: 24,
    ),
  ),
  cardTheme: const CardThemeData(
    elevation: 4,
    shadowColor: Colors.black26,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.all(Radius.circular(16)),
    ),
    color: Color(0xFF1E1E1E),
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      elevation: 2,
      backgroundColor: const Color(0xFF66BB6A),
      foregroundColor: const Color(0xFF1B5E20),
      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
      ),
      textStyle: GoogleFonts.inter(
        fontSize: 14,
        fontWeight: FontWeight.w600,
        letterSpacing: 0.1,
      ),
    ),
  ),
  bottomAppBarTheme: const BottomAppBarTheme(
    color: Color(0xFF121212),
    elevation: 8,
  ),
  iconTheme: const IconThemeData(
    color: Color(0xFFBDBDBD),
    size: 24,
  ),
  drawerTheme: const DrawerThemeData(
    backgroundColor: Color(0xFF121212),
    surfaceTintColor: Color(0xFF121212),
  ),
);
